# Generated by Django 5.2.15 on 2026-09-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_order_customer_deleted_alter_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Статистика и аналитика',
                'verbose_name_plural': 'Статистика и аналитика',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
    ]
