# Generated by Django 5.2.16 on 2026-07-08 17:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrule',
            name='comment',
            field=models.TextField(blank=True, help_text='Необязательно. Внутренние пояснения для менеджеров.', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='deliveryrule',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, help_text='Обязательно. Базовая стоимость доставки в рублях.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='deliveryrule',
            name='delivery_zone',
            field=models.CharField(blank=True, help_text='Необязательно. Район или город, к которому применяется правило.', max_length=255, verbose_name='Зона доставки'),
        ),
        migrations.AlterField(
            model_name='deliveryrule',
            name='free_delivery_from',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Необязательно. При сумме заказа от этой величины доставка бесплатна.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Бесплатная доставка от суммы'),
        ),
        migrations.AlterField(
            model_name='deliveryrule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Только активные правила участвуют в расчёте доставки.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='deliveryrule',
            name='name',
            field=models.CharField(help_text='Обязательно. Понятное название правила для менеджеров.', max_length=255, verbose_name='Название'),
        ),
    ]
