# Generated by Django 5.2.15 on 2026-08-25 15:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_deliveryrule_comment_and_more'),
        ('intake', '0005_orderdraft_contact_email_orderdraft_contact_phone'),
        ('orders', '0005_order_customer_email_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider', models.CharField(choices=[('yandex_russia', 'Яндекс Доставка по России'), ('local_rule', 'Локальное правило')], default='yandex_russia', max_length=32, verbose_name='Провайдер')),
                ('environment', models.CharField(choices=[('test', 'Тестовый контур'), ('production', 'Коммерческий контур'), ('local', 'Локальный режим')], default='test', max_length=16, verbose_name='Контур')),
                ('kind', models.CharField(choices=[('preliminary', 'Предварительная оценка'), ('offer', 'Оффер для бронирования'), ('fallback', 'Локальный fallback')], default='preliminary', max_length=16, verbose_name='Тип расчёта')),
                ('status', models.CharField(choices=[('succeeded', 'Рассчитан'), ('failed', 'Ошибка'), ('expired', 'Истёк'), ('selected', 'Выбран')], default='succeeded', max_length=16, verbose_name='Статус')),
                ('request_fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='Отпечаток запроса')),
                ('operator_request_id', models.CharField(blank=True, max_length=128, verbose_name='Внутренний ID запроса')),
                ('external_offer_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='ID оффера Яндекса')),
                ('last_mile_policy', models.CharField(choices=[('time_interval', 'Курьер до двери'), ('self_pickup', 'Пункт выдачи')], default='time_interval', max_length=16, verbose_name='Последняя миля')),
                ('destination_address', models.TextField(verbose_name='Адрес (снимок)')),
                ('package_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Вес и габариты (снимок)')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Стоимость доставки')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('delivery_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Расчётный срок, дней')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('delivery_from', models.DateTimeField(blank=True, null=True, verbose_name='Доставка с')),
                ('delivery_to', models.DateTimeField(blank=True, null=True, verbose_name='Доставка до')),
                ('pickup_from', models.DateTimeField(blank=True, null=True, verbose_name='Забор с')),
                ('pickup_to', models.DateTimeField(blank=True, null=True, verbose_name='Забор до')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='Запрос')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='Ответ')),
                ('error_code', models.CharField(blank=True, max_length=128, verbose_name='Код ошибки')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_quotes', to='orders.order', verbose_name='Заказ')),
                ('order_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_quotes', to='intake.orderdraft', verbose_name='Черновик заказа')),
            ],
            options={
                'verbose_name': 'Расчёт доставки',
                'verbose_name_plural': 'Расчёты доставки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider', models.CharField(choices=[('yandex_russia', 'Яндекс Доставка по России'), ('local_rule', 'Локальное правило')], default='yandex_russia', max_length=32, verbose_name='Провайдер')),
                ('environment', models.CharField(choices=[('test', 'Тестовый контур'), ('production', 'Коммерческий контур'), ('local', 'Локальный режим')], default='test', max_length=16, verbose_name='Контур')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirming', 'Подтверждается'), ('confirmed', 'Подтверждено'), ('in_transit', 'В пути'), ('delivered', 'Доставлено'), ('cancelled', 'Отменено'), ('failed', 'Ошибка')], default='draft', max_length=16, verbose_name='Статус')),
                ('external_request_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='ID заявки Яндекса')),
                ('external_status', models.CharField(blank=True, max_length=128, verbose_name='Статус Яндекса')),
                ('tracking_url', models.URLField(blank=True, max_length=1000, verbose_name='Трекинг')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Стоимость доставки')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('delivery_from', models.DateTimeField(blank=True, null=True, verbose_name='Доставка с')),
                ('delivery_to', models.DateTimeField(blank=True, null=True, verbose_name='Доставка до')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Синхронизировано')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('creation_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload создания')),
                ('provider_payload', models.JSONField(blank=True, default=dict, verbose_name='Последний ответ')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='orders.order', verbose_name='Заказ')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='delivery.deliveryquote', verbose_name='Выбранный расчёт')),
            ],
            options={
                'verbose_name': 'Доставка заказа',
                'verbose_name_plural': 'Доставки заказов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('operation', models.CharField(choices=[('pricing', 'Расчёт'), ('offers_create', 'Создание офферов'), ('offer_confirm', 'Подтверждение оффера'), ('info', 'Получение статуса'), ('cancel', 'Отмена'), ('poll', 'Синхронизация')], max_length=24)),
                ('succeeded', models.BooleanField(default=False, verbose_name='Успешно')),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='delivery.deliveryquote', verbose_name='Расчёт')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='delivery.shipment', verbose_name='Доставка')),
            ],
            options={
                'verbose_name': 'Событие синхронизации доставки',
                'verbose_name_plural': 'События синхронизации доставки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deliveryquote',
            index=models.Index(fields=['provider', 'environment', 'status', 'created_at'], name='delivery_quote_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryquote',
            constraint=models.UniqueConstraint(condition=models.Q(('external_offer_id', ''), _negated=True), fields=('provider', 'environment', 'external_offer_id'), name='delivery_unique_external_offer'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(condition=models.Q(('external_request_id', ''), _negated=True), fields=('provider', 'environment', 'external_request_id'), name='delivery_unique_external_request'),
        ),
        migrations.AddConstraint(
            model_name='deliverysyncevent',
            constraint=models.CheckConstraint(condition=models.Q(('shipment__isnull', False), ('quote__isnull', False), _connector='OR'), name='delivery_sync_event_has_target'),
        ),
    ]
