# Generated by Django 5.2.15 on 2026-08-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryquote_shipment_deliverysyncevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('confirming', 'Подтверждается'), ('confirmed', 'Подтверждено'), ('in_transit', 'В пути'), ('delivered', 'Доставлено'), ('cancelling', 'Отменяется'), ('cancelled', 'Отменено'), ('failed', 'Ошибка')], default='draft', max_length=16, verbose_name='Статус'),
        ),
    ]
