# Generated by Django 5.2 on 2026-09-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0004_alter_cart_channel"),
        ("delivery", "0004_alter_shipment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryquote",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_quotes",
                to="carts.cart",
                verbose_name="Корзина",
            ),
        ),
    ]
