# Generated by Django 5.2.15 on 2026-09-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_deliveryquote_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='next_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sync_failures',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
