# Generated by Django 5.2.15 on 2026-08-24 15:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_product_base_price_alter_product_description_and_more'),
        ('customers', '0005_alter_customer_first_source_and_more'),
        ('orders', '0004_alter_order_channel_alter_orderstatushistory_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX'), ('website', 'Сайт'), ('email', 'Email')], max_length=16, verbose_name='Канал')),
                ('external_user_id', models.CharField(max_length=255, verbose_name='ID пользователя')),
                ('conversation_key', models.CharField(max_length=255, verbose_name='Ключ диалога')),
                ('intent', models.CharField(choices=[('create_order', 'Создать заказ'), ('modify_order', 'Изменить заказ'), ('cancel_order', 'Отменить заказ'), ('order_status', 'Узнать статус заказа'), ('product_question', 'Вопрос о товаре'), ('unknown', 'Не определено')], default='unknown', max_length=32, verbose_name='Намерение')),
                ('status', models.CharField(choices=[('collecting', 'Сбор данных'), ('needs_clarification', 'Требуется уточнение'), ('ready_for_preview', 'Готов к расчёту'), ('awaiting_confirmation', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('converted', 'Преобразован в заказ'), ('cancelled', 'Отменён'), ('escalated', 'Передан менеджеру'), ('failed', 'Ошибка')], default='collecting', max_length=32, verbose_name='Статус')),
                ('receiving_type', models.CharField(blank=True, choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], max_length=16, verbose_name='Способ получения')),
                ('desired_date', models.DateField(blank=True, null=True, verbose_name='Желаемая дата')),
                ('desired_time_interval', models.CharField(blank=True, choices=[('10-12', '10:00–12:00'), ('12-14', '12:00–14:00'), ('14-16', '14:00–16:00'), ('16-18', '16:00–18:00'), ('18-20', '18:00–20:00'), ('20-22', '20:00–22:00')], max_length=8, verbose_name='Интервал времени')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('payment_method', models.CharField(blank=True, choices=[('cash_on_delivery', 'Наличные при получении'), ('card_on_delivery', 'Карта при получении'), ('card_prepayment', 'Предоплата картой')], max_length=32, verbose_name='Способ оплаты')),
                ('customer_comment', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('missing_fields', models.JSONField(blank=True, default=list, verbose_name='Недостающие поля')),
                ('manager_attention_required', models.BooleanField(default=False, verbose_name='Требуется менеджер')),
                ('escalation_reason', models.TextField(blank=True, verbose_name='Причина передачи')),
                ('revision', models.PositiveIntegerField(default=1, verbose_name='Версия черновика')),
                ('previewed_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('confirmed_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('items_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('priced_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассчитан')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждён')),
                ('converted_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_draft', to='orders.order', verbose_name='Созданный заказ')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_drafts', to='customers.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Черновик AI-заказа',
                'verbose_name_plural': 'Черновики AI-заказов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX'), ('website', 'Сайт'), ('email', 'Email')], max_length=16, verbose_name='Канал')),
                ('external_event_id', models.CharField(max_length=255, verbose_name='ID события в канале')),
                ('external_user_id', models.CharField(max_length=255, verbose_name='ID пользователя')),
                ('conversation_key', models.CharField(max_length=255, verbose_name='Ключ диалога')),
                ('kind', models.CharField(choices=[('message', 'Сообщение'), ('callback', 'Действие интерфейса'), ('form_submission', 'Отправка формы')], default='message', max_length=24, verbose_name='Тип события')),
                ('raw_text', models.TextField(blank=True, verbose_name='Исходный текст')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('payload_schema_version', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Версия payload')),
                ('status', models.CharField(choices=[('received', 'Получено'), ('queued', 'В очереди'), ('processing', 'Обрабатывается'), ('retry_scheduled', 'Ожидает повтора'), ('processed', 'Обработано'), ('failed', 'Ошибка'), ('ignored', 'Пропущено')], default='received', max_length=24, verbose_name='Статус')),
                ('processing_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попытки')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало обработки')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_events', to='customers.customer', verbose_name='Клиент')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='intake.orderdraft', verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Входящее событие',
                'verbose_name_plural': 'Входящие события',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Clarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('field_path', models.CharField(max_length=255, verbose_name='Путь поля')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('answered', 'Получен ответ'), ('skipped', 'Пропущено'), ('cancelled', 'Отменено')], default='pending', max_length=16)),
                ('answer_text', models.TextField(blank=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('asked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_by_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_clarifications', to='intake.inboundevent')),
                ('trigger_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_clarifications', to='intake.inboundevent')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='intake.orderdraft', verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Уточнение',
                'verbose_name_plural': 'Уточнения',
                'ordering': ['-asked_at'],
            },
        ),
        migrations.CreateModel(
            name='AIExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('extraction', 'Извлечение заказа'), ('clarification', 'Формирование уточнения'), ('disambiguation', 'Разрешение неоднозначности'), ('repair', 'Исправление структуры')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('succeeded', 'Успешно'), ('schema_invalid', 'Ошибка схемы'), ('provider_error', 'Ошибка провайдера'), ('skipped', 'Пропущено')], default='pending', max_length=24)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('prompt_id', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=32)),
                ('input_hash', models.CharField(max_length=64)),
                ('raw_response', models.TextField(blank=True)),
                ('structured_output', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_runs', to='intake.inboundevent', verbose_name='Событие')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs', to='intake.orderdraft', verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Запуск AI-извлечения',
                'verbose_name_plural': 'Запуски AI-извлечения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDraftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('line_number', models.PositiveIntegerField(verbose_name='Номер позиции')),
                ('raw_product_name', models.CharField(max_length=255, verbose_name='Название из запроса')),
                ('requested_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество')),
                ('requested_unit', models.CharField(blank=True, choices=[('kg', 'Килограмм'), ('piece', 'Штука'), ('package', 'Упаковка')], max_length=16, verbose_name='Единица')),
                ('match_status', models.CharField(choices=[('unresolved', 'Не сопоставлен'), ('matched', 'Сопоставлен'), ('ambiguous', 'Несколько вариантов'), ('not_found', 'Не найден'), ('invalid', 'Некорректен')], default='unresolved', max_length=16, verbose_name='Сопоставление')),
                ('candidate_product_ids', models.JSONField(blank=True, default=list)),
                ('resolution_source', models.CharField(blank=True, choices=[('exact', 'Точное совпадение'), ('alias', 'Синоним'), ('trigram', 'Нечёткий поиск'), ('semantic', 'Семантический поиск'), ('customer', 'Уточнено клиентом'), ('manager', 'Уточнено менеджером')], max_length=16, verbose_name='Источник сопоставления')),
                ('resolution_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Уверенность')),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='intake.orderdraft', verbose_name='Черновик')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_items', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция черновика',
                'verbose_name_plural': 'Позиции черновика',
                'ordering': ['line_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='orderdraft',
            index=models.Index(fields=['status', 'updated_at'], name='intake_draft_status_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdraft',
            index=models.Index(fields=['channel', 'conversation_key', 'created_at'], name='intake_draft_conversation_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('collecting', 'needs_clarification', 'ready_for_preview', 'awaiting_confirmation', 'confirmed'))), fields=('channel', 'conversation_key'), name='intake_unique_active_draft_per_conversation'),
        ),
        migrations.AddIndex(
            model_name='inboundevent',
            index=models.Index(fields=['status', 'next_retry_at'], name='intake_event_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundevent',
            index=models.Index(fields=['channel', 'conversation_key', 'created_at'], name='intake_event_conversation_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboundevent',
            constraint=models.UniqueConstraint(fields=('channel', 'external_event_id'), name='intake_unique_channel_event'),
        ),
        migrations.AddConstraint(
            model_name='clarification',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('draft', 'field_path'), name='intake_unique_pending_clarification'),
        ),
        migrations.AddIndex(
            model_name='aiextractionrun',
            index=models.Index(fields=['status', 'created_at'], name='intake_ai_run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='aiextractionrun',
            index=models.Index(fields=['prompt_id', 'prompt_version'], name='intake_ai_prompt_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderdraftitem',
            constraint=models.UniqueConstraint(fields=('draft', 'line_number'), name='intake_unique_draft_line'),
        ),
        migrations.AddConstraint(
            model_name='orderdraftitem',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity__isnull', True), ('requested_quantity__gt', 0), _connector='OR'), name='intake_draft_item_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='orderdraftitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('match_status', 'matched'), _negated=True), ('product__isnull', False), _connector='OR'), name='intake_matched_item_has_product'),
        ),
    ]
