# Generated by Django 5.2.15 on 2026-08-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundevent',
            name='processing_token',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='Токен обработки'),
        ),
    ]
