# Generated by Django 5.2.15 on 2026-08-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_inboundevent_processing_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdraftitem',
            name='resolution_source',
            field=models.CharField(blank=True, choices=[('exact', 'Точное совпадение'), ('alias', 'Синоним'), ('trigram', 'Нечёткий поиск'), ('fuzzy', 'Unicode fuzzy-поиск'), ('semantic', 'Семантический поиск'), ('customer', 'Уточнено клиентом'), ('manager', 'Уточнено менеджером')], max_length=16, verbose_name='Источник сопоставления'),
        ),
    ]
