# Generated by Django 5.2.15 on 2026-08-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_outboundmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdraft',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=320, verbose_name='Email для текущего заказа'),
        ),
        migrations.AddField(
            model_name='orderdraft',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Телефон для текущего заказа'),
        ),
    ]
