# Generated by Django 5.2.15 on 2026-09-04 13:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0005_orderdraft_contact_email_orderdraft_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('succeeded', 'Успешно'), ('failed', 'Ошибка'), ('tool_limit', 'Лимит инструментов')], default='running', max_length=24)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('prompt_profile', models.CharField(blank=True, max_length=64)),
                ('model_calls', models.PositiveSmallIntegerField(default=0)),
                ('tool_calls', models.PositiveSmallIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_turns', to='intake.orderdraft')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assistant_turn', to='intake.inboundevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('call_index', models.PositiveSmallIntegerField()),
                ('tool_name', models.CharField(max_length=64)),
                ('arguments', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('succeeded', 'Успешно'), ('failed', 'Ошибка'), ('rejected', 'Отклонено')], default='running', max_length=24)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='intake.assistantturn')),
            ],
            options={
                'ordering': ['call_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('conversation_key', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(choices=[('user', 'Клиент'), ('assistant', 'Ассистент')], max_length=16)),
                ('content', models.TextField()),
                ('response_type', models.CharField(blank=True, max_length=32)),
                ('action_url', models.URLField(blank=True, max_length=2000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistant_messages', to='intake.inboundevent')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['conversation_key', 'created_at'], name='intake_assistant_history_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'role'), name='intake_unique_assistant_message_role')],
            },
        ),
        migrations.AddIndex(
            model_name='assistantturn',
            index=models.Index(fields=['status', 'created_at'], name='intake_assistant_turn_idx'),
        ),
        migrations.AddConstraint(
            model_name='assistanttoolcall',
            constraint=models.UniqueConstraint(fields=('turn', 'call_index'), name='intake_unique_tool_call_index'),
        ),
    ]
