# Generated by Django 5.2.15 on 2026-09-08 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cart_desired_date_cart_desired_time_interval_and_more'),
        ('intake', '0006_assistantturn_assistanttoolcall_assistantmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdraft',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='carts.cart'),
        ),
        migrations.AddField(
            model_name='orderdraft',
            name='checkout_preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='carts.checkoutpreview'),
        ),
        migrations.AddField(
            model_name='orderdraft',
            name='synced_cart_revision',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
