# Generated by Django 5.2.15 on 2026-09-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0007_orderdraft_cart_orderdraft_checkout_preview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('channel', models.CharField(max_length=16)),
                ('external_user_id', models.CharField(max_length=255)),
                ('conversation_key', models.CharField(max_length=255)),
                ('last_question', models.TextField(blank=True)),
                ('options', models.JSONField(default=list)),
                ('selected_product_code', models.CharField(blank=True, max_length=32)),
                ('expected_fields', models.JSONField(default=list)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('channel', 'external_user_id', 'conversation_key'), name='unique_conversation_memory')],
            },
        ),
    ]
