# Generated by Django 5.2.15 on 2026-09-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0008_conversationmemory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdraft',
            options={'ordering': ['-created_at'], 'verbose_name': 'Диалог AI-ассистента', 'verbose_name_plural': 'Диалоги и заказы'},
        ),
    ]
