# Generated by Django 5.2.15 on 2026-07-03 13:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('public_number', models.CharField(max_length=32, unique=True, verbose_name='Номер заказа')),
                ('customer_code_snapshot', models.CharField(max_length=32, verbose_name='Код клиента (snapshot)')),
                ('customer_name_snapshot', models.CharField(max_length=255, verbose_name='Имя клиента (snapshot)')),
                ('customer_phone_snapshot', models.CharField(max_length=11, verbose_name='Телефон клиента (snapshot)')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'VK'), ('max', 'MAX'), ('website', 'Сайт'), ('phone', 'Телефон'), ('manager', 'Менеджер')], max_length=16, verbose_name='Канал')),
                ('is_new_customer', models.BooleanField(default=False, verbose_name='Новый клиент')),
                ('receiving_type', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], max_length=16, verbose_name='Способ получения')),
                ('desired_date', models.DateField(blank=True, null=True, verbose_name='Желаемая дата')),
                ('desired_time_interval', models.CharField(blank=True, choices=[('10-12', '10:00–12:00'), ('12-14', '12:00–14:00'), ('14-16', '14:00–16:00'), ('16-18', '16:00–18:00'), ('18-20', '18:00–20:00'), ('20-22', '20:00–22:00')], max_length=8, verbose_name='Интервал времени')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('customer_comment', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('items_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма товаров')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Скидка')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Доставка')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Итого')),
                ('order_status', models.CharField(choices=[('new', 'Новый'), ('assembled', 'Собран'), ('delivering', 'Доставляется'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='new', max_length=16, verbose_name='Статус заказа')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачен'), ('waiting', 'Ожидает оплаты'), ('paid', 'Оплачен')], default='unpaid', max_length=16, verbose_name='Статус оплаты')),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'Наличные при получении'), ('card_on_delivery', 'Карта при получении'), ('card_prepayment', 'Предоплата картой')], max_length=32, verbose_name='Способ оплаты')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=255, verbose_name='Название товара (snapshot)')),
                ('product_unit_snapshot', models.CharField(max_length=16, verbose_name='Единица измерения (snapshot)')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма позиции')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('old_status', models.CharField(blank=True, choices=[('new', 'Новый'), ('assembled', 'Собран'), ('delivering', 'Доставляется'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], max_length=16, verbose_name='Старый статус')),
                ('new_status', models.CharField(choices=[('new', 'Новый'), ('assembled', 'Собран'), ('delivering', 'Доставляется'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], max_length=16, verbose_name='Новый статус')),
                ('source', models.CharField(choices=[('telegram', 'Telegram'), ('django_admin', 'Django Admin'), ('website', 'Сайт'), ('api', 'API'), ('automatic', 'Автоматически')], max_length=16, verbose_name='Источник')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-event_datetime'],
            },
        ),
    ]
