# Generated by Django 5.2.15 on 2026-07-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX'), ('website', 'Сайт'), ('phone', 'Телефон'), ('manager', 'Менеджер')], max_length=16, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_code_snapshot',
            field=models.CharField(max_length=32, verbose_name='Код клиента (снимок)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name_snapshot',
            field=models.CharField(max_length=255, verbose_name='Имя клиента (снимок)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone_snapshot',
            field=models.CharField(max_length=11, verbose_name='Телефон клиента (снимок)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name_snapshot',
            field=models.CharField(max_length=255, verbose_name='Название товара (снимок)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_unit_snapshot',
            field=models.CharField(max_length=16, verbose_name='Единица измерения (снимок)'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='source',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('django_admin', 'Админ-панель Django'), ('website', 'Сайт'), ('api', 'API'), ('automatic', 'Автоматически')], max_length=16, verbose_name='Источник'),
        ),
    ]
