# Generated by Django 5.2.15 on 2026-07-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX'), ('website', 'Сайт')], max_length=16, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='source',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX'), ('django_admin', 'Админ-панель Django'), ('website', 'Сайт'), ('api', 'API'), ('automatic', 'Автоматически')], max_length=16, verbose_name='Источник'),
        ),
    ]
