# Generated by Django 5.2.15 on 2026-08-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_channel_alter_orderstatushistory_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email_snapshot',
            field=models.EmailField(blank=True, max_length=320, verbose_name='Email клиента (снимок)'),
        ),
        migrations.AddField(
            model_name='order',
            name='source_external_user_id_snapshot',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID пользователя/обращения в канале (снимок)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone_snapshot',
            field=models.CharField(blank=True, max_length=11, verbose_name='Телефон клиента (снимок)'),
        ),
    ]
