# Generated by Django 5.2.17 on 2026-09-07 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_personal_data_consent_registry_key'),
        ('orders', '0005_order_customer_email_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_deleted',
            field=models.BooleanField(default=False, help_text='Карточка клиента удалена, персональные данные в заказе обезличены.', verbose_name='Клиент удалён'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer', verbose_name='Клиент'),
        ),
    ]
