# Generated by Django 5.2.17 on 2026-09-05 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0006_customeridentityconflict_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDataDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_type', models.CharField(choices=[('privacy_policy', 'Политика обработки персональных данных'), ('personal_data_consent', 'Согласие на обработку персональных данных')], max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('effective_from', models.DateField()),
                ('content', models.TextField()),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('public_path', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Версия документа ПДн',
                'verbose_name_plural': 'Версии документов ПДн',
                'ordering': ['document_type', '-effective_from', '-id'],
                'constraints': [models.UniqueConstraint(fields=('document_type', 'version'), name='privacy_unique_document_version')],
            },
        ),
        migrations.CreateModel(
            name='PersonalDataConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identity_type', models.CharField(choices=[('telegram_user_id', 'Telegram user ID'), ('vk_user_id', 'VK user ID'), ('max_user_id', 'MAX user ID'), ('website_session_id', 'ID сессии сайта')], max_length=32)),
                ('identity_value', models.CharField(max_length=255)),
                ('identification_level', models.CharField(choices=[('platform_account', 'ID аккаунта платформы'), ('website_session', 'ID сессии сайта')], max_length=32)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX'), ('website', 'Сайт'), ('email', 'Email')], max_length=16)),
                ('source', models.CharField(max_length=64)),
                ('purpose', models.CharField(default='Обработка персональных данных для работы сервиса и исполнения заказа', max_length=255)),
                ('status', models.CharField(choices=[('granted', 'Дано'), ('declined', 'Отказ'), ('withdrawn', 'Отозвано'), ('superseded', 'Заменено новой версией')], max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('expression_method', models.CharField(choices=[('website_checkbox', 'Чекбокс сайта'), ('bot_button', 'Кнопка бота'), ('website_withdrawal', 'Форма отзыва на сайте'), ('bot_command', 'Команда бота')], max_length=32)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_data_consent_events', to='customers.customer')),
                ('previous_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_events', to='privacy.personaldataconsentevent')),
                ('consent_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_events', to='privacy.personaldatadocumentversion')),
                ('policy_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_events', to='privacy.personaldatadocumentversion')),
            ],
            options={
                'verbose_name': 'Событие согласия ПДн',
                'verbose_name_plural': 'Реестр согласий ПДн',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['channel', 'identity_value', '-occurred_at'], name='privacy_per_channel_5a8b9c_idx')],
            },
        ),
    ]
