# Generated by Django 5.2.17 on 2026-09-07 12:47

from django.db import migrations


def publish_versions(apps, schema_editor):
    # Сервис содержит текст версии 1.1; get_or_create не меняет уже
    # опубликованные записи и фиксирует их хеш моделью.
    from apps.privacy.services import ConsentService

    ConsentService.current_documents()


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
    ]

    operations = [migrations.RunPython(publish_versions, migrations.RunPython.noop)]
