# Generated by Django 5.2.15 on 2026-07-03 13:32

import apps.customers.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('public_code', models.CharField(max_length=32, unique=True, verbose_name='Код клиента')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=11, validators=[apps.customers.validators.validate_phone], verbose_name='Телефон')),
                ('first_source', models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'VK'), ('max', 'MAX'), ('website', 'Сайт'), ('phone', 'Телефон'), ('manager', 'Менеджер')], max_length=16, verbose_name='Первый источник')),
                ('first_order_at', models.DateTimeField(blank=True, null=True, verbose_name='Первый заказ')),
                ('last_order_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний заказ')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='Количество заказов')),
                ('total_orders_sum', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Сумма заказов')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('active', 'Активный'), ('sleeping', 'Спящий'), ('vip', 'VIP'), ('blacklisted', 'Чёрный список')], default='new', max_length=16, verbose_name='Статус')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='Согласие на маркетинг')),
                ('personal_data_consent', models.BooleanField(default=False, verbose_name='Согласие на обработку ПД')),
                ('personal_data_consent_link', models.URLField(blank=True, verbose_name='Ссылка на согласие')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerChannelIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'VK'), ('max', 'MAX'), ('website', 'Сайт')], max_length=16, verbose_name='Канал')),
                ('external_user_id', models.CharField(max_length=128, verbose_name='ID пользователя')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_identities', to='customers.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Канал клиента',
                'verbose_name_plural': 'Каналы клиентов',
                'constraints': [models.UniqueConstraint(fields=('channel', 'external_user_id'), name='unique_channel_external_user')],
            },
        ),
    ]
