# Generated by Django 5.2.15 on 2026-07-03 14:24

import apps.customers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_source',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX'), ('website', 'Сайт'), ('phone', 'Телефон'), ('manager', 'Менеджер')], max_length=16, verbose_name='Первый источник'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[apps.customers.validators.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('active', 'Активный'), ('sleeping', 'Спящий'), ('vip', 'ВИП'), ('blacklisted', 'Чёрный список')], default='new', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='customerchannelidentity',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX'), ('website', 'Сайт')], max_length=16, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='customerchannelidentity',
            name='external_user_id',
            field=models.CharField(max_length=128, verbose_name='Идентификатор пользователя'),
        ),
        migrations.AlterField(
            model_name='customerchannelidentity',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
