# Generated by Django 5.2.15 on 2026-07-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_first_source_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Телефон подтверждён'),
        ),
        migrations.AddConstraint(
            model_name='customerchannelidentity',
            constraint=models.UniqueConstraint(fields=('customer', 'channel'), name='unique_customer_channel'),
        ),
    ]
