# Generated by Django 5.2.16 on 2026-07-08 17:57

import apps.customers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_phone_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_source',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX'), ('website', 'Сайт'), ('phone', 'Телефон'), ('manager', 'Менеджер')], help_text='Обязательно. При ручном создании в админке выберите «Менеджер».', max_length=16, verbose_name='Первый источник'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='manager_comment',
            field=models.TextField(blank=True, help_text='Необязательно. Внутренние заметки, не видны клиенту.', verbose_name='Комментарий менеджера'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Обязательно. Имя клиента для заказов и CRM.', max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Обязательно. Формат хранения: 79991234567 (11 цифр, начинается с 7). Можно ввести +7, 8… или 10 цифр с 9 — система приведёт к единому виду.', max_length=11, unique=True, validators=[apps.customers.validators.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text='Заполняется автоматически при подтверждении через бота или API. Вручную — только при проверке менеджером.', null=True, verbose_name='Телефон подтверждён'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='public_code',
            field=models.CharField(help_text='Создаётся автоматически при сохранении. Вручную заполнять не нужно.', max_length=32, unique=True, verbose_name='Код клиента'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('active', 'Активный'), ('sleeping', 'Спящий'), ('vip', 'ВИП'), ('blacklisted', 'Чёрный список')], default='new', help_text='По умолчанию «Новый». Меняется автоматически после первого заказа.', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='customerchannelidentity',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX'), ('website', 'Сайт')], help_text='Обязательно. Платформа: Telegram, ВКонтакте, MAX или сайт.', max_length=16, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='customerchannelidentity',
            name='external_user_id',
            field=models.CharField(help_text='Обязательно. ID пользователя в выбранном канале (например, telegram user id).', max_length=128, verbose_name='Идентификатор пользователя'),
        ),
        migrations.AlterField(
            model_name='customerchannelidentity',
            name='username',
            field=models.CharField(blank=True, help_text='Необязательно. @username или ник в канале.', max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
