# Generated by Django 5.2.15 on 2026-08-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_first_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_source',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX'), ('website', 'Сайт'), ('email', 'Email'), ('phone', 'Телефон'), ('manager', 'Менеджер')], help_text='Обязательно. При ручном создании в админке выберите «Менеджер».', max_length=16, verbose_name='Первый источник'),
        ),
        migrations.AlterField(
            model_name='customerchannelidentity',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX'), ('website', 'Сайт'), ('email', 'Email')], help_text='Обязательно. Платформа: Telegram, ВКонтакте, MAX, сайт или email.', max_length=16, verbose_name='Канал'),
        ),
    ]
