# Generated by Django 5.2.15 on 2026-08-25 14:28

import apps.customers.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_first_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerIdentityConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('contact_type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email')], max_length=16, verbose_name='Тип контакта')),
                ('contact_value', models.CharField(db_index=True, max_length=320, verbose_name='Нормализованный контакт')),
                ('source_channel', models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX'), ('website', 'Сайт'), ('email', 'Email')], max_length=16, verbose_name='Канал обнаружения')),
                ('source_external_user_id', models.CharField(blank=True, max_length=255, verbose_name='ID пользователя/обращения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает решения'), ('merged', 'Карточки объединены'), ('kept_separate', 'Оставлены раздельно'), ('ignored', 'Проигнорирован')], default='pending', max_length=24, verbose_name='Статус')),
                ('resolution_comment', models.TextField(blank=True, verbose_name='Решение менеджера')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Решён')),
            ],
            options={
                'verbose_name': 'Конфликт идентификации',
                'verbose_name_plural': 'Конфликты идентификации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='customerchannelidentity',
            name='unique_customer_channel',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', help_text='Необязательно. Хранится в нормализованном нижнем регистре.', max_length=320, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='Заполняется после подтверждения владения почтовым адресом.', null=True, verbose_name='Email подтверждён'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Необязательно для email-клиента. Формат хранения: 79991234567. Можно ввести +7, 8… или 10 цифр с 9 — система приведёт к единому виду.', max_length=11, validators=[apps.customers.validators.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('phone', ''), _negated=True), models.Q(('email', ''), _negated=True), _connector='OR'), name='customers_customer_has_contact'),
        ),
        migrations.AddField(
            model_name='customeridentityconflict',
            name='matched_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matched_identity_conflicts', to='customers.customer', verbose_name='Совпавшая карточка'),
        ),
        migrations.AddField(
            model_name='customeridentityconflict',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_customer_identity_conflicts', to=settings.AUTH_USER_MODEL, verbose_name='Решил'),
        ),
        migrations.AddField(
            model_name='customeridentityconflict',
            name='source_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_conflicts', to='customers.customer', verbose_name='Текущая карточка'),
        ),
        migrations.AddIndex(
            model_name='customeridentityconflict',
            index=models.Index(fields=['status', 'created_at'], name='customers_conflict_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeridentityconflict',
            constraint=models.CheckConstraint(condition=models.Q(('source_customer', models.F('matched_customer')), _negated=True), name='customers_identity_conflict_different_customers'),
        ),
        migrations.AddConstraint(
            model_name='customeridentityconflict',
            constraint=models.UniqueConstraint(fields=('source_customer', 'matched_customer', 'contact_type', 'contact_value', 'source_channel'), name='customers_unique_identity_conflict'),
        ),
    ]
