# Generated by Django 5.2.17 on 2026-09-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customeridentityconflict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='personal_data_consent_registry_key',
            field=models.UUIDField(blank=True, editable=False, help_text='UUID актуального события в электронном реестре. Не является ссылкой на файл согласия.', null=True, verbose_name='Ключ записи реестра согласий'),
        ),
    ]
