# Generated by Django 5.2.17 on 2026-09-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_personal_data_consent_registry_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='personal_data_consent_link',
        ),
    ]
