# Generated by Django 5.2.15 on 2026-09-08 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_authguard_logincode_webaccount_orderaccessgrant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincode',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_codes', to='customers.webaccount'),
        ),
        migrations.AddField(
            model_name='logincode',
            name='purpose',
            field=models.CharField(default='login', max_length=24),
        ),
    ]
