# Generated by Django 5.2.15 on 2026-09-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_logincode_account_logincode_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='websessionbinding',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
