# Generated by Django 5.2.15 on 2026-07-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX'), ('website', 'Сайт')], max_length=16, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='external_user_id',
            field=models.CharField(max_length=128, verbose_name='Идентификатор пользователя'),
        ),
    ]
