# Generated by Django 5.2.16 on 2026-07-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_channel_alter_cart_external_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX'), ('website', 'Сайт')], help_text='Обязательно. Платформа, в которой создана корзина.', max_length=16, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='external_user_id',
            field=models.CharField(help_text='Обязательно. ID пользователя в канале (совпадает с привязкой клиента).', max_length=128, verbose_name='Идентификатор пользователя'),
        ),
    ]
