# Generated by Django 5.2.15 on 2026-08-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cart_channel_alter_cart_external_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX'), ('website', 'Сайт'), ('email', 'Email')], help_text='Обязательно. Платформа, в которой создана корзина.', max_length=16, verbose_name='Канал'),
        ),
    ]
