# Generated by Django 5.2.15 on 2026-09-08 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cart_checkout_state'),
        ('customers', '0008_remove_customer_personal_data_consent_link'),
        ('delivery', '0005_deliveryquote_cart'),
        ('orders', '0006_order_customer_deleted_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='desired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='desired_time_interval',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='cart',
            name='revision',
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
        migrations.CreateModel(
            name='CheckoutPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cart_revision', models.PositiveBigIntegerField()),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='previews', to='carts.cart')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('quote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.deliveryquote')),
            ],
        ),
    ]
