# Generated by Django 5.2.15 on 2026-08-26 12:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_order_customer_email_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider', models.CharField(choices=[('yookassa', 'ЮKassa')], default='yookassa', max_length=32, verbose_name='Провайдер')),
                ('environment', models.CharField(choices=[('test', 'Тестовый магазин'), ('production', 'Коммерческий магазин')], default='test', max_length=16, verbose_name='Контур')),
                ('state', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('waiting_for_capture', 'Ожидает списания'), ('succeeded', 'Оплачен'), ('canceled', 'Отменён'), ('failed', 'Ошибка создания')], default='pending', max_length=24, verbose_name='Состояние')),
                ('idempotence_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Ключ идемпотентности')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='ID платежа ЮKassa')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
                ('confirmation_url', models.URLField(blank=True, max_length=2000, verbose_name='Ссылка на оплату')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('cancellation_code', models.CharField(blank=True, max_length=128)),
                ('cancellation_description', models.TextField(blank=True)),
                ('receipt_data', models.JSONField(blank=True, default=dict, verbose_name='Данные чека')),
                ('provider_payload', models.JSONField(blank=True, default=dict, verbose_name='Ответ ЮKassa')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider', models.CharField(choices=[('yookassa', 'ЮKassa')], max_length=32)),
                ('event_type', models.CharField(blank=True, max_length=128)),
                ('fingerprint', models.CharField(max_length=64, unique=True, verbose_name='Отпечаток')),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('verified', models.BooleanField(default=False, verbose_name='Проверено у провайдера')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('processing_error', models.TextField(blank=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.payment', verbose_name='Платёж')),
            ],
            options={
                'verbose_name': 'Webhook платежа',
                'verbose_name_plural': 'Webhook-события платежей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('state', models.CharField(choices=[('pending', 'Обрабатывается'), ('succeeded', 'Возвращён'), ('canceled', 'Отменён'), ('failed', 'Ошибка')], default='pending', max_length=24, verbose_name='Состояние')),
                ('idempotence_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Ключ идемпотентности')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('reason', models.CharField(blank=True, max_length=256)),
                ('receipt_data', models.JSONField(blank=True, default=dict)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment', verbose_name='Платёж')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'state', 'created_at'], name='payments_order_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('provider', 'environment', 'external_id'), name='payments_unique_external_payment'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('payment', 'external_id'), name='payments_unique_external_refund'),
        ),
    ]
