# Generated by Django 5.2 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="paid_notification_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_notification_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_notification_sent_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Уведомление об оплате отправлено",
            ),
        ),
    ]
