# Generated by Django 5.2 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_paid_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="receipt_registration_error",
            field=models.TextField(blank=True, verbose_name="Ошибка регистрации чека"),
        ),
        migrations.AddField(
            model_name="payment",
            name="receipt_registration_status",
            field=models.CharField(
                blank=True,
                max_length=32,
                verbose_name="Статус регистрации чека",
            ),
        ),
    ]
