# Generated by Django 5.2.15 on 2026-09-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_receipt_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='allocations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
