# Generated by Django 5.2.16 on 2026-07-08 17:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountrule',
            name='date_end',
            field=models.DateField(blank=True, help_text='Необязательно. Правило действует до этой даты включительно.', null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='date_start',
            field=models.DateField(blank=True, help_text='Необязательно. Правило действует с этой даты включительно.', null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Укажите процент или фиксированную сумму (или оба — применяется по логике сервиса).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Скидка, %'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='free_delivery',
            field=models.BooleanField(default=False, help_text='Если включено, правило даёт бесплатную доставку при выполнении условий.', verbose_name='Бесплатная доставка'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Только активные правила участвуют в расчёте скидок.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='name',
            field=models.CharField(help_text='Обязательно. Понятное название правила для менеджеров.', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='Обязательно. Меньшее число — выше приоритет при нескольких подходящих правилах.', verbose_name='Приоритет'),
        ),
    ]
