# Generated by Django 5.2.15 on 2026-07-03 13:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('public_code', models.CharField(max_length=32, unique=True, verbose_name='Код товара')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('unit', models.CharField(choices=[('kg', 'Килограмм'), ('piece', 'Штука'), ('package', 'Упаковка')], default='piece', max_length=16, verbose_name='Единица измерения')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Минимальное количество')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Базовая цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='catalog_pro_is_acti_903fcc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt-текст')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
