# Generated by Django 5.2.16 on 2026-07-08 17:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Обязательно. Цена за единицу измерения в рублях.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Необязательно. Текст для карточки товара.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть товар из каталога без удаления.', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Обязательно. Название товара в каталоге и заказах.', max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='public_code',
            field=models.CharField(help_text='Создаётся автоматически при сохранении. Вручную заполнять не нужно.', max_length=32, unique=True, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Килограмм'), ('piece', 'Штука'), ('package', 'Упаковка')], default='piece', help_text='Обязательно. Штуки, килограммы и т.д.', max_length=16, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Необязательно. Описание изображения для доступности.', max_length=255, verbose_name='Альтернативный текст'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Одно фото товара должно быть отмечено как главное.', verbose_name='Главное фото'),
        ),
    ]
