# Generated by Django 5.2.15 on 2026-08-24 16:15

import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_base_price_alter_product_description_and_more'),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('alias', models.CharField(max_length=255, verbose_name='Синоним')),
                ('normalized_alias', models.CharField(db_index=True, editable=False, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Синоним товара',
                'verbose_name_plural': 'Синонимы товаров',
                'ordering': ['alias', 'id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'normalized_alias'), name='catalog_unique_product_alias')],
            },
        ),
    ]
