# Generated by Django 5.2.15 on 2026-08-25 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_height_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Габарит одной единицы товара. Обязателен для Яндекс Доставки.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Высота упаковки, см'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_length_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Габарит одной единицы товара. Обязателен для Яндекс Доставки.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длина упаковки, см'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_weight_grams',
            field=models.PositiveIntegerField(blank=True, help_text='Вес брутто одной единицы товара. Для товара в килограммах укажите вес одного килограмма — 1000 г. Обязателен для расчёта Яндекс Доставки.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вес для доставки, г'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_width_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Габарит одной единицы товара. Обязателен для Яндекс Доставки.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ширина упаковки, см'),
        ),
    ]
